name: cd

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  Deploy:
    name: Deploy APP to ElasticBeanstalk
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set Up Npm
        run: |
          sudo apt install npm

      - name: Npm init
        working-directory: code
        run: npm i

      - name: Install python
        working-directory: code
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install python3 python3-pip -y
          python3 --version
          pip3 --version

      - name: Install EB Cli
        working-directory: code
        run: |
          pip3 install awsebcli --upgrade --user
          export PATH=$PATH:~/.local/bin
          eb --version

      - name: Deploy
        working-directory: code
        run: |
          eb init  --region us-east-1 --platform "Python 3.8" --interactive false --no-verify-ssl
          echo "global:" > .elasticbeanstalk/config.yml
          echo "  application_name: my-app" >> .elasticbeanstalk/config.yml
          echo "  default_region: us-east-1" >> .elasticbeanstalk/config.yml
          echo "  platform: Python 3.8" >> .elasticbeanstalk/config.yml
          echo "  workspace_type: Application" >> .elasticbeanstalk/config.yml
          eb create
          eb deploy
